# This is a real Dockerfile that will build CentOS6
FROM centos:latest
LABEL maintainer="mridao@gmail.com"

RUN yum update -y && \
    yum -y install httpd net-tools && \
    mkdir -p /run/httpd && \
    rm -rf /run/http/* /tmp/httpd/*

CMD echo "Remember to check your container IP Address"

ENV ENVIRONMENT="production"

EXPOSE 80

ENTRYPOINT apachectl "-DFOREGROUND"
