# This is a real Dockerfile that will build CentOS6
FROM centos:latest
LABEL maintainer="mridao@gmail.com"

RUN yum update -y
RUN yum -y install httpd net-tools
RUN mkdir -p /run/httpd
RUN rm -rf /run/http/* /tmp/httpd/*

CMD echo "Remember to check your container IP Address"

ENV ENVIRONMENT="production"

EXPOSE 80

ENTRYPOINT apachectl "-DFOREGROUND"
