# This is a real Dockerfile that will build CentOS6
ARG TAGVERSION=latest
FROM centos:${TAGVERSION}

LABEL maintainer="mridao@gmail.com"

RUN yum update -y && \
    yum -y install httpd net-tools && \
    mkdir -p /run/httpd && \
    rm -rf /run/http/* /tmp/httpd/*

COPY index.html /var/www/html/

CMD echo "Remember to check your container IP Address"

ENV ENVIRONMENT="production"

VOLUME /mymount

EXPOSE 80

ENTRYPOINT apachectl "-DFOREGROUND"
